environment:
  sonarlogin:
    secure: sao5EE3hl2It2xv4colifAIVz134RLHv1yYijwuacL2uF2evx8F5p3P2SNZC6Lm4
before_build:
  - nuget restore Temporary_TradeTicker_Placeholder\Temporary_TradeTicker_Placeholder.sln
build_script:
#  - choco install "msbuild-sonarqube-runner" -y
#  - MSBuild.SonarQube.Runner.exe begin /k:Tradeticker /d:sonar.host.url=https://sonarqube.com /d:sonar.login=%sonarlogin% /o:edwinvr-github /v:"%appveyor_build_version%
  - msbuild "Temporary_TradeTicker_Placeholder\Temporary_TradeTicker_Placeholder.sln"
#  - MSBuild.SonarQube.Runner.exe end /d:sonar.login=%sonarlogin%
artifacts:
  - path: Temporary_TradeTicker_Placeholder\bin\Debug\*
    name: mybuild
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  artifact: mybuild
  auth_token:
    secure: SY+6iEMqUlbzMcvBp6VHamJCMs7sMLTFYy1BLHvsDT12GxTQxrmZRvxuLKxW+9Aq # your encrypted token from GitHub
  draft: false
  prerelease: false
  on:
    branch: hello-world                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only